use todo;

-- MySQL Script generated by MySQL Workbench
-- Fri Feb 14 20:53:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todo` DEFAULT CHARACTER SET utf8 ;
USE `todo` ;

-- -----------------------------------------------------
-- Table `todo`.`timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`timestamps` ;

CREATE TABLE IF NOT EXISTS `todo`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `todo`.`DbUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`DbUser` ;

CREATE TABLE IF NOT EXISTS `todo`.`DbUser` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `sms` VARCHAR(16) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`Todo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`Todo` ;

CREATE TABLE IF NOT EXISTS `todo`.`Todo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `deadline` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `DbUser_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Todo_DbUser1_idx` (`DbUser_id` ASC) VISIBLE,
  CONSTRAINT `fk_Todo_DbUser1`
    FOREIGN KEY (`DbUser_id`)
    REFERENCES `todo`.`DbUser` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`Comment` ;

CREATE TABLE IF NOT EXISTS `todo`.`Comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `body` VARCHAR(500) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `DbUser_id` INT NOT NULL,
  `Todo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comment_DbUser1_idx` (`DbUser_id` ASC) VISIBLE,
  INDEX `fk_Comment_Todo1_idx` (`Todo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_DbUser1`
    FOREIGN KEY (`DbUser_id`)
    REFERENCES `todo`.`DbUser` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Comment_Todo1`
    FOREIGN KEY (`Todo_id`)
    REFERENCES `todo`.`Todo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`Category` ;

CREATE TABLE IF NOT EXISTS `todo`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`TodoCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`TodoCategory` ;

CREATE TABLE IF NOT EXISTS `todo`.`TodoCategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Category_id` INT NOT NULL,
  `Todo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TodoCategory_Category_idx` (`Category_id` ASC) VISIBLE,
  INDEX `fk_TodoCategory_Todo1_idx` (`Todo_id` ASC) VISIBLE,
  CONSTRAINT `fk_TodoCategory_Category`
    FOREIGN KEY (`Category_id`)
    REFERENCES `todo`.`Category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TodoCategory_Todo1`
    FOREIGN KEY (`Todo_id`)
    REFERENCES `todo`.`Todo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`DbUserCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`DbUserCategory` ;

CREATE TABLE IF NOT EXISTS `todo`.`DbUserCategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `DbUser_id` INT NOT NULL,
  `Category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_DbUserCategory_DbUser1_idx` (`DbUser_id` ASC) VISIBLE,
  INDEX `fk_DbUserCategory_Category1_idx` (`Category_id` ASC) VISIBLE,
  CONSTRAINT `fk_DbUserCategory_DbUser1`
    FOREIGN KEY (`DbUser_id`)
    REFERENCES `todo`.`DbUser` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DbUserCategory_Category1`
    FOREIGN KEY (`Category_id`)
    REFERENCES `todo`.`Category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`TodoHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`TodoHistory` ;

CREATE TABLE IF NOT EXISTS `todo`.`TodoHistory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `old_title` VARCHAR(100) NOT NULL,
  `new_title` VARCHAR(100) NOT NULL,
  `changed_at` TIMESTAMP NOT NULL,
  `Todo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TodoHistory_Todo1_idx` (`Todo_id` ASC) VISIBLE,
  CONSTRAINT `fk_TodoHistory_Todo1`
    FOREIGN KEY (`Todo_id`)
    REFERENCES `todo`.`Todo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
