services:
  mysql:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo
    ports:
      - 3307:3306 # Port 3306 is already in use in my machine, so I'm using 3307
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql